import { Provider } from "react-redux"

import "./globals.css"
import store from "@/app/store"
import AppHeader from "@/app/components/AppHeader"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <AppHeader />
          {children}
        </Provider>
      </body>
    </html>
  )
}
